-h|--help added ; misc

diff --git a/bin/git-timesync b/bin/git-timesync
--- a/bin/git-timesync
+++ b/bin/git-timesync
@@ -33,13 +33,26 @@ set -e
 ####
 
 showUsage() {
-	echo "Usage: git-timesync [OPTION]... [FILE]..."
+	echo 'Usage: git-timesync [-n] [-q] [-v] [--] [<paths>...]'
+	echo 'Usage: git-timesync [-n] [-q] [-v] -<N>'
 	echo
-	echo "  -h, --help                  Print this help message"
-	echo "  -n, --dry-run, --dryrun     Perform a dry-run to see which files" \
-		"are OK and which ones need to be synchronized"
-	echo "  -q, --quiet                 Quiet mode: drop everything that is" \
-		"OK and show only the files which timestamp needs to be synchronized"
+	echo '  -h, --help                 '\
+		'Print this help message'
+	echo '  -n, --dry-run, --dryrun    '\
+		'Perform a dry-run to see which files are OK'\
+		'and which ones need to be synchronized'
+	echo '  -q, --quiet                '\
+		'Quiet mode: drop everything that is OK and show only the files'\
+		'which timestamp needs to be synchronized'
+	echo '  -v, --verbose              '\
+		'Verbose mode: show info for each file (opposite of --quiet)'
+	echo '  -1                         '\
+		'Apply timesync on files present in the last commit'
+	echo '  -23                        '\
+		'Apply timesync on files present in the 23 last commits'
+	echo '  -N                         '\
+		'Apply timesync on files present in the N last commits'\
+		'(with 1 <= N <= 9999)'
 }
 
 # Get the last revision hash of a particular file in the git repository
@@ -120,7 +133,7 @@ updateFileTimeStamp() {
 }
 
 # ... for FreeBSD and Mac OS X
-updateFileTimeStamp2() {
+updateFileTimeStampBSD() {
 	# Extract the file revision
 	local FILE_REVISION_HASH="$(getFileLastRevision "$1")"
 
@@ -163,6 +176,19 @@ updateFileTimeStampInCwd() {
 	)
 }
 
+timesyncThisFile() {
+	if [ -d "$1" ] && [ ! -h "$1" ]; then # is a real directory (not a symlink to a directory)
+		echo "now inside $1"
+		( cd -- "$1" && updateFileTimeStampInCwd || true; )
+	else
+		if $need_check_bare; then
+			is_not_base_repo || continue
+			need_check_bare=false
+		fi
+		updateFileTimeStamp "$1"
+	fi
+}
+
 ################################################################################
 ############################## MAIN SCRIPT LOGIC ###############################
 ################################################################################
@@ -174,11 +200,13 @@ fromrecent=''
 while [ $# -gt 0 ]; do
 	case "$1" in
 		--) shift; break ;;
+		-h|--help) showUsage; exit 0;;
 		-n|--dryrun|--dry-run) dryrun=true ;;
 		-v) verbose=true ;;
 		-q) verbose=false ;;
 		-[1-9]|-[1-9][0-9]|-[1-9][0-9][0-9]|-[1-9][0-9][0-9][0-9]) fromrecent="$1" ;;
 		--debug) debug=true ;;
+		-*) echo >&2 "$0: invalid option $1"; exit 1;;
 		*) break
 	esac
 	shift
@@ -188,7 +216,7 @@ done
 case "${OS:-$(uname)}" in
 	  'Linux') ;;
 	  'Darwin'|'FreeBSD')
-		updateFileTimeStamp() { updateFileTimeStamp2 "$@"; }
+		updateFileTimeStamp() { updateFileTimeStampBSD "$@"; }
 	  ;;
 	  *)
 		echo >&2 "Unknown Operating System to perform timestamp update"
@@ -200,19 +228,6 @@ if [ $# -eq 0 ] && [ -z "$fromrecent" ]; then
 	updateFileTimeStampInCwd
 else
 	need_check_bare=true
-
-	timesyncThisFile() {
-		if [ -d "$1" ] && [ ! -h "$1" ]; then # is a real directory (not a symlink to a directory)
-			echo "now inside $1"
-			( cd -- "$1" && updateFileTimeStampInCwd || true; )
-		else
-			if $need_check_bare; then
-				is_not_base_repo || continue
-				need_check_bare=false
-			fi
-			updateFileTimeStamp "$1"
-		fi
-	}
 
 	# Loop through and fix timestamps on all specified files
 	if [ -n "$fromrecent" ]; then
